- hosts: all
  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop:
        - "gnupg"
        - "python3-pip"

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Install Docker-Compose Module for Python
      pip:
        name: docker-compose

- name: Run MonicaHQ with Docker Compose
  hosts: all
  gather_facts: no
  tasks:
    - docker_compose:
        project_name: ripper
        definition:
          version: "2"
          services:
            ripper:
              image: nitupkcuf/ddos-ripper:latest
              command: "{{ lookup(env, 'TARGET_HOST') }}"

    - ansible.builtin.assert:
        that:
          - "ripper.ripper_ripper_1.state.running"
